#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Check if the correct number of arguments is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the provided arguments to variables
file_to_transfer="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_to_transfer" "$username@$server_ip":~/

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File '$file_to_transfer' successfully transferred to $username@$server_ip:~/"
else
    echo "Error: File transfer failed."
    exit 1
fi
