#!/usr/bin/env bash
#This script it to configures a new Ubuntu machine to Perform a 301-redirection

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# code to redire https://github.com/InfinityJer permanently
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/InfinityJer permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
