#!/usr/bin/env bash

# Install Nginx if not already installed
if ! dpkg -l | grep -q nginx; then
    apt-get update -y
    apt-get install nginx -y
fi

# Create a custom HTML page for the 404 error
echo -e '<!DOCTYPE html>\n<html>\n<head><title>404 Not Found</title></head>\n<body>\n<h1>404 Not Found</h1>\n<p>Ceci n\'est pas une page</p>\n</body>\n</html>' | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
echo -e "error_page 404 /404.html;\nlocation = /404.html {\n    internal;\n}" | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Ensure Nginx is listening on port 80
sed -i '/listen 80 default_server;/c\listen 80;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
