#!/usr/bin/env bash
# Install Nginx if not already installed
# Configures new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# code to redirect to YouTube site (Ex. redirect_me to www.youtube.com)
echo 'Hello World!' | sudo tee /var/www/html/index.html
newString="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$newString/" /etc/nginx/sites-enabled/default

# Configure Nginx to use the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
newStringTwo="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$newStringTwo/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
