#!/usr/bin/env bash
#Customizes a 404 page

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# code to redire https://github.com/InfinityJer permanently
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/InfinityJer permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# restart the server
sudo service nginx restart
