#!/usr/bin/env bash
# installs and confiures haproxy on new ubuntu machine

# Install HAproxy on a server
sudo apt update
sudo apt install haproxy -y

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend infinity-jer.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 279540-web-01 18.207.2.67:80 check
        server 279540-web-02 52.91.120.49:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
