#!/bin/bash

# Create a variable for the current date in the desired format
CURRENT_DATE=$(date +'%d-%m-%Y')

# Create the MySQL dump
mysqldump -u root -p$1 --all-databases > backup.sql

# Create a compressed archive
tar -czvf "$CURRENT_DATE.tar.gz" backup.sql

# Clean up the generated SQL file
rm backup.sql
