#!/bin/bash
# Bash scrit to archive all MySQL DATABASE with the help of mysqldump and tar 

# Create the MySQL dump
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Create a compressed archive with current date in the desired format
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
