#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# in a user-oriented format, including those without a TTY, and showing the process hierarchy.
# Using the ps command to list all processes for all users and showing process hierarchy.
ps aux uf
