#!/usr/bin/env bash
# Bash script that stops the 4-to_infinity_and_beyond process.
# Function to stop the 4-to_infinity_and_beyond process
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
