#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely
# with a sleep 2 in between each iteration and responds to SIGTERM signal with "I am invincible!!!"
# Function to handle the SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
