#!/usr/bin/env bash
# Bash script that kills the 7-highlander process.
# Find the PID of the 7-highlander process
YOUR_7_HIGHLANDER_PID=$(pgrep -f "7-highlander")
# Check if the PID is valid
if [[ -n "$YOUR_7_HIGHLANDER_PID" ]]; then
    # Terminate the process
    echo "Killing the 7-highlander process..."
    kill -9 "$YOUR_7_HIGHLANDER_PID"
else
    echo "7-highlander process not found!"
fi
