#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Set a counter variable to track the number of iterations
counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -ge 10 ]; do
    echo "Best School"
    ((counter++))
done
