#!/usr/bin/env bash
# This script displays "Best School" 10 times, saying "Hi" on the 9th iteration

# Set a counter variable to track the number of iterations
counter=1

# Using a while loop with an if statement to display "Best School" 10 times
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
