#!/usr/bin/env bash
# This script displays different messages based on the loop iteration

# Set a counter variable to track the number of iterations
counter=1

# Using a while loop with if, elif, and else statements to display messages
while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
