#!/usr/bin/env bash

# Change localhost resolution to 127.0.0.2 in the hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Change facebook.com resolution to 8.8.8.8 in the hosts file
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
