#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine executed
# Use 'ifconfig' command to get active IPv4 addresses, filter out loopback and inactive addresses
ifconfig | grep -o "inet [^ ]*" | cut -d ":" -f2 | cut -d " " -f2
