#!/usr/bin/env bash

# Use 'ifconfig' command to get active IPv4 addresses, filter out loopback and inactive addresses
ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | awk '{print $2}'
