#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user and listen on port 8080

# Update the Nginx configuration to run as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# apache may interfere with nginx so kill the process if it is running
pkill apache2

# Restart Nginx to apply the changes
sudo -u nginx service nginx start
