#!/usr/bin/env bash
# This script connects to a server using SSH and a private key

# Connect to the server using SSH with the specified private key and user
ssh -i ~/.ssh/school ubuntu@100.26.243.19
